MvcEditorTemplate/Models/MainVm.cs
namespace MvcEditorTemplate.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    public class MainVm
    {
        public MainVm()
        {
            this.PersonsList = new List<PersonVm>();
        }
        public List<PersonVm> PersonsList { get; set; }
    }
}

MvcEditorTemplate/Models/PersonVm.cs
namespace MvcEditorTemplate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;

    public class PersonVm
    {
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
}

MvcEditorTemplate/Controllers/EditorTemplateController.cs
namespace MvcEditorTemplate.Controllers
{
    using MvcEditorTemplate.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class EditorTemplateController : Controller
    {
        public ActionResult Index()
        {
            var vm = new MainVm();
            var pList = new List<PersonVm>();

            // Mock our person list - KISS :)
            for (int i = 1; i <= 5; i++)
            {
                var p = new PersonVm();

                p.PersonId = i;
                p.FirstName = "Person " + i;
                p.LastName = "Surname " + i;
                p.DateOfBirth = new DateTime(1980, 5, 3).AddYears(i);

                pList.Add(p);
            }
            vm.PersonsList = pList;

            return View(vm);
        }

        [HttpPost]
        public ActionResult Index(MainVm vm, string btnSubmitPerson)
        {
            // Verify which button was pressed and act accordingly.
            if(!string.IsNullOrEmpty(btnSubmitPerson))
            {
                // Do something with data that was posted back.
            }
            return View(vm);
        }
    }
}

MvcEditorTemplate/Views/EditorTemplate/Index.cshtml
@model MvcEditorTemplate.Models.MainVm

@using (Html.BeginForm())
{
    <h2>Editor template - by index</h2>
    @Html.EditorFor(m => m, "PersonVmByIdx")
}

MvcEditorTemplate/Views/Shared/EditorTemplates/PersonVmByIdx.cshtml
@model MvcEditorTemplate.Models.MainVm

<ul class="nav nav-tabs">
    @{
        for (int i = 0; i < Model.PersonsList.Count; i++)
        {
            <li class="@(i == 0 ? "active" : "")"><a data-toggle="tab" href="#personTab@(Model.PersonsList[i].PersonId)">Person @Model.PersonsList[i].PersonId</a></li>
        }
    }
</ul>

<div class="tab-content">
    @{

        for (int i = 0; i < Model.PersonsList.Count; i++)
        {
            <div id="personTab@(Model.PersonsList[i].PersonId)" class="tab-pane fade in @(i == 0 ? "active" : "")">
                <h3>@Model.PersonsList[i].FirstName @Model.PersonsList[i].LastName</h3>
                <table>
                    <tr>
                        <td>Id</td>
                        <td>@Html.EditorFor(m => m.PersonsList[i].PersonId)</td>
                    </tr>
                    <tr>
                        <td>First name</td>
                        <td>@Html.EditorFor(m => m.PersonsList[i].FirstName)</td>
                    </tr>
                    <tr>
                        <td>Last name</td>
                        <td>@Html.EditorFor(m => m.PersonsList[i].LastName)</td>
                    </tr>
                    <tr>
                        <td>Date of birth</td>
                        <td>@Html.EditorFor(m => m.PersonsList[i].DateOfBirth)</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <button id="btnSubmit@(Model.PersonsList[i].PersonId)" type="submit" value="btnSubmitPerson@(Model.PersonsList[i].PersonId)" name="btnSubmitPerson">Submit</button>
                        </td>
                    </tr>
                </table>
            </div>
        }
    }
</div>

MvcEditorTemplate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Editor Template (Model) example</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "EditorTemplate", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("EditorTemplate test", "Index", "EditorTemplate")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>